import type { NextPage } from 'next';
import Head from 'next/head';
import HeaderPanell from "../components/header.panel";
import { IQuery } from "../dto/query";
import {IUser} from "../dto/user";
import {createContext, useEffect, useState} from "react";
import {number} from "prop-types";

interface ILayoutDefault {
  title: string,
  user: IUser,
  query: IQuery,
};

export const DataContext = createContext({
  user: {} as IUser,
  query: {} as IQuery,
  win: Date.now(),
});

const LayoutDefault: NextPage<ILayoutDefault> = ({title, user, query, children,}) => {
  const [win, setWin] = useState<number>(Date.now());

  useEffect(() => {
    if(window) window.addEventListener('click', () => setWin(Date.now()))
  },[])

  return (
    <DataContext.Provider value={{user,query,win}}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <HeaderPanell />
      </header>
      <main id="main">
        <div className="container">{children}</div>
      </main>
      <footer id="footer"></footer>
    </DataContext.Provider>
  )
};

export default LayoutDefault;